import { ArrowUpRight, BarChart3, Brain, Check, Database, LayoutDashboard, Menu, MessageCircle, Play, Sparkles, TrendingUp, X } from 'lucide-react'
import { useState } from 'react'
import './marketing.css'

const services = [
  ['Data Analysis & Insight', 'Find the signal inside your operational data.', BarChart3],
  ['Interactive Dashboards', 'Give every decision-maker a live view of performance.', LayoutDashboard],
  ['Python & ML Modeling', 'Forecast demand, risk, and growth with confidence.', Brain],
  ['Data Cleaning & ETL', 'Turn fragmented sources into a dependable data foundation.', Sparkles],
  ['BI Strategy', 'Align metrics, teams, and action around one source of truth.', TrendingUp],
  ['Market Research', 'See competitors clearly and move before the market does.', Database],
] as const
const featured = [
  ['Revenue Intelligence', 'A live command center for your most important growth metrics.', '$12k–$28k'],
  ['Predictive Demand Model', 'Know what your customers need before they ask.', '$18k–$42k'],
  ['Executive KPI Suite', 'One calm, credible view for every leadership decision.', '$8k–$20k'],
  ['Data Foundation Sprint', 'Clean pipelines and a source of truth your team can trust.', '$6k–$16k'],
]
const caseStudies = [['Retail growth engine', '+32%', 'Revenue lift'], ['Inventory intelligence', '$2.3M', 'Annual savings'], ['Fintech forecasting', '94%', 'Forecast accuracy']]
const testimonials = [
  ['“DataVision gave our leadership team a shared language for growth. We moved from weekly debates to daily decisions.”', 'Maya Chen', 'COO, TechRetail'],
  ['“The dashboard paid for itself in the first quarter. More importantly, our team finally trusts the numbers.”', 'Arjun Mehta', 'VP Operations, GlobalLogistics'],
  ['“They combine strategic thinking with serious technical depth. It feels like adding a senior analytics team overnight.”', 'Elena Brooks', 'Founder, FinanceFirst'],
]
const tech = ['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'PyTorch', 'Power BI', 'Tableau', 'Looker', 'SQL', 'PostgreSQL', 'BigQuery', 'Snowflake', 'dbt', 'Apache Spark', 'Airflow', 'Excel', 'Plotly', 'D3.js', 'Streamlit', 'Supabase']
const stats = [['150+', 'Projects delivered'], ['98%', 'Client satisfaction'], ['$12M+', 'Client revenue generated'], ['12+', 'Industries served']]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [testimonial, setTestimonial] = useState(0)
  return <main>
    <nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">D</span> DataVision</a><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#services">Services</a><a href="#process">How it works</a><a href="#results">Results</a><a href="#contact">Contact</a></div><a className="button button-small" href="#contact">Book a free audit <ArrowUpRight size={16} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></nav>
    <section id="top" className="hero shell"><div className="orb orb-one" /><div className="orb orb-two" /><div className="hero-copy"><div className="eyebrow"><span className="pulse" /> Trusted by 50+ data-driven companies</div><h1>Turn raw data into <em>decisive advantage.</em></h1><p className="hero-lede">We design dashboards, build ML models, and deliver insights that measurably grow revenue, cut costs, and eliminate guesswork—for teams that refuse to fly blind.</p><div className="actions"><a className="button" href="#contact">Book a free audit <ArrowUpRight size={18} /></a><a className="button button-ghost" href="#portfolio">See our work <Play size={15} /></a></div><div className="trust-strip"><span>★ 4.9 avg rating</span><span>98% retention</span><span>50+ projects</span><span>12+ industries</span></div></div><DashboardPreview /></section>
    <section className="logo-bar"><div className="logo-track">{['TechRetail', 'MedCenter', 'GlobalLogistics', 'FinanceFirst', 'PropInvest', 'BrandBoost'].map((logo) => <span key={logo}>{logo}</span>)}</div></section>
    <section id="services" className="section shell"><SectionIntro eyebrow="What we do" title="Everything you need to become data-driven" copy="From raw spreadsheets to revenue-driving dashboards, we handle the entire analytics lifecycle." /><div className="service-grid">{services.map(([title, copy, Icon]) => <article className="glass-card service-card" key={title}><div className="icon-tile"><Icon size={22} /></div><h3>{title}</h3><p>{copy}</p><a href="#contact">Learn more <ArrowUpRight size={15} /></a></article>)}</div></section>
    <section id="process" className="section section-muted"><div className="shell"><SectionIntro eyebrow="How we work" title="From chaos to clarity in four steps" copy="A focused, collaborative process that turns uncertainty into momentum." /><div className="process-grid">{['Discovery call', 'Data audit & strategy', 'Build & analyze', 'Deliver, train & support'].map((step, i) => <div className="process-step" key={step}><span>{String(i + 1).padStart(2, '0')}</span><h3>{step}</h3><p>{['We listen to the questions keeping you up at night.', 'We map sources, find gaps, and design the plan.', 'We clean, model, and visualize with weekly check-ins.', 'You get dashboards, docs, and 30-day support.'][i]}</p></div>)}</div></div></section>
    <section className="section shell story-section"><div className="story-copy"><p className="eyebrow">Why you need this</p><h2>Data should remove friction—not create more of it.</h2><p>When reporting lives in scattered spreadsheets and instinct drives the big calls, growth becomes expensive. We build the calm, connected layer between your data and your next best decision.</p><ul>{['+32% average revenue lift after dashboard rollout', '−40% reduction in reporting time via automation', '$2.3M saved annually on inventory waste', '94% forecast accuracy with our ML models'].map((item) => <li key={item}><Check size={18} /> {item}</li>)}</ul></div><div className="signal-card"><div className="signal-orbit" /><div className="signal-center"><span>Signal</span><strong>↗</strong><small>from noise</small></div><span className="signal-label label-one">Revenue</span><span className="signal-label label-two">Retention</span><span className="signal-label label-three">Demand</span></div></section>
    <section className="section section-muted"><div className="shell"><SectionIntro eyebrow="Featured services" title="Start with the question that matters most" copy="Focused engagements designed to create momentum quickly, then compound into a stronger data operating system." /><div className="featured-grid">{featured.map(([title, copy, price], i) => <article className="featured-card" key={title}><span className="card-index">0{i + 1}</span><h3>{title}</h3><p>{copy}</p><strong>{price}</strong><a href="#contact">Explore engagement <ArrowUpRight size={15} /></a></article>)}</div></div></section>
    <section id="portfolio" className="section shell"><SectionIntro eyebrow="Selected outcomes" title="The work speaks in numbers" copy="A few examples of what happens when teams replace fragmented reporting with useful intelligence." /><div className="case-grid">{caseStudies.map(([title, value, label], i) => <article className={`case-card case-${i + 1}`} key={title}><span>Case study / 0{i + 1}</span><strong>{value}</strong><h3>{title}</h3><p>{label}</p><a href="#contact">View outcome <ArrowUpRight size={15} /></a></article>)}</div></section>
    <section className="section section-muted testimonial-section"><div className="shell"><SectionIntro eyebrow="Client perspective" title="Good analytics changes the conversation" copy="The best proof is what happens inside the room after the dashboard goes live." /><div className="testimonial-card"><div className="stars">★★★★★</div><blockquote>{testimonials[testimonial][0]}</blockquote><div className="testimonial-person"><span>{testimonials[testimonial][1].split(' ').map((n) => n[0]).join('')}</span><div><strong>{testimonials[testimonial][1]}</strong><small>{testimonials[testimonial][2]}</small></div></div><div className="testimonial-controls">{testimonials.map((_, i) => <button className={i === testimonial ? 'active' : ''} onClick={() => setTestimonial(i)} aria-label={`Show testimonial ${i + 1}`} key={i} />)}</div></div></div></section>
    <section className="section shell tech-section"><SectionIntro eyebrow="Our toolkit" title="We speak fluent data" copy="The right tools matter. The right architecture matters more. We choose what makes your team faster." /><div className="tech-grid">{tech.map((item, i) => <span key={item} style={{ animationDelay: `${i * 35}ms` }}>{item}</span>)}</div></section>
    <section id="results" className="stats-section"><div className="shell"><p className="eyebrow">The DataVision effect</p><h2>Built to earn its keep.</h2><div className="stats-grid">{stats.map(([value, label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div></section>
    <section id="contact" className="cta shell"><div><p className="eyebrow">Ready when you are</p><h2>Make data your unfair advantage.</h2><p>Book a free 30-minute audit. We’ll show you where you’re losing money—and how to fix it.</p></div><a className="button" href="mailto:hello@datavision.agency">Book free audit <ArrowUpRight size={18} /></a></section><footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">D</span> DataVision</a><span>Analytics that earns its keep.</span><span>© 2026 DataVision</span></footer><a className="chat-fab" href="mailto:hello@datavision.agency" aria-label="Contact DataVision"><MessageCircle size={20} /></a>
  </main>
}
function SectionIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="section-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div> }
function DashboardPreview() { return <div className="dashboard-wrap"><div className="dashboard-card"><div className="dashboard-head"><span>Revenue intelligence</span><span className="live"><i /> Live</span></div><div className="kpi-row"><div><small>Net revenue</small><strong>$284,920</strong><span className="positive">↗ 32.8%</span></div><div><small>Forecast confidence</small><strong>94.2%</strong><span className="positive">↗ 8.4%</span></div></div><div className="chart"><div className="chart-grid" /><svg viewBox="0 0 420 150" preserveAspectRatio="none"><path d="M0 130 C35 120 45 90 75 102 S120 118 150 82 S195 105 225 64 S270 72 300 45 S350 50 375 18 S405 28 420 4" fill="none" stroke="url(#line)" strokeWidth="4" strokeLinecap="round" /><defs><linearGradient id="line" x1="0" x2="1"><stop stopColor="#22d3ee" /><stop offset="1" stopColor="#6366f1" /></linearGradient></defs></svg></div><div className="dashboard-foot"><span>Performance trend</span><span>Last 30 days <ArrowUpRight size={13} /></span></div></div></div> }
export default App
