import { ArrowUpRight, BarChart3, Brain, Check, Database, LayoutDashboard, Menu, Sparkles, TrendingUp, X } from 'lucide-react'
import { useState } from 'react'

const services = [
  ['Data Analysis & Insight', 'Find the signal inside your operational data.', BarChart3],
  ['Interactive Dashboards', 'Give every decision-maker a live view of performance.', LayoutDashboard],
  ['Python & ML Modeling', 'Forecast demand, risk, and growth with confidence.', Brain],
  ['Data Cleaning & ETL', 'Turn fragmented sources into a dependable data foundation.', Sparkles],
  ['BI Strategy', 'Align metrics, teams, and action around one source of truth.', TrendingUp],
  ['Market Research', 'See competitors clearly and move before the market does.', Database],
] as const

const stats = [['150+', 'Projects delivered'], ['98%', 'Client satisfaction'], ['$12M+', 'Revenue generated'], ['12+', 'Industries served']]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main>
    <nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">D</span> DataVision</a><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#services">Services</a><a href="#process">How it works</a><a href="#results">Results</a><a href="#contact">Contact</a></div><a className="button button-small" href="#contact">Book a free audit <ArrowUpRight size={16} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></nav>
    <section id="top" className="hero shell"><div className="orb orb-one" /><div className="orb orb-two" /><div className="hero-copy"><div className="eyebrow"><span className="pulse" /> Trusted by 50+ data-driven companies</div><h1>Turn raw data into <em>decisive advantage.</em></h1><p className="hero-lede">We design dashboards, build ML models, and deliver insights that measurably grow revenue, cut costs, and eliminate guesswork.</p><div className="actions"><a className="button" href="#contact">Book a free audit <ArrowUpRight size={18} /></a><a className="button button-ghost" href="#results">See our work</a></div><div className="trust-strip"><span>★ 4.9 avg rating</span><span>98% retention</span><span>50+ projects</span><span>12+ industries</span></div></div><DashboardPreview /></section>
    <section className="logo-bar"><div className="logo-track">{['TechRetail', 'MedCenter', 'GlobalLogistics', 'FinanceFirst', 'PropInvest', 'BrandBoost'].map((logo) => <span key={logo}>{logo}</span>)}</div></section>
    <section id="services" className="section shell"><SectionIntro eyebrow="What we do" title="Everything you need to become data-driven" copy="From raw spreadsheets to revenue-driving dashboards, we handle the entire analytics lifecycle." /><div className="service-grid">{services.map(([title, copy, Icon]) => <article className="glass-card service-card" key={title}><div className="icon-tile"><Icon size={22} /></div><h3>{title}</h3><p>{copy}</p><a href="#contact">Learn more <ArrowUpRight size={15} /></a></article>)}</div></section>
    <section id="process" className="section section-muted"><div className="shell"><SectionIntro eyebrow="How we work" title="From chaos to clarity in four steps" copy="A focused, collaborative process that turns uncertainty into momentum." /><div className="process-grid">{['Discovery call', 'Data audit & strategy', 'Build & analyze', 'Deliver, train & support'].map((step, i) => <div className="process-step" key={step}><span>{String(i + 1).padStart(2, '0')}</span><h3>{step}</h3><p>{['We listen to the questions keeping you up at night.', 'We map sources, find gaps, and design the plan.', 'We clean, model, and visualize with weekly check-ins.', 'You get dashboards, docs, and 30-day support.'][i]}</p></div>)}</div></div></section>
    <section id="results" className="section shell"><SectionIntro eyebrow="The outcome" title="Stop guessing. Start moving with evidence." copy="The right data product compounds into faster decisions, healthier margins, and a team that knows exactly what to do next." /><div className="stats-grid">{stats.map(([value, label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="impact-grid"><div><p className="eyebrow">Why DataVision</p><h2>Clarity is a competitive advantage.</h2><ul>{['+32% average revenue lift after dashboard rollout', '−40% reduction in reporting time via automation', '$2.3M saved annually on inventory waste', '94% forecast accuracy with our ML models'].map((item) => <li key={item}><Check size={18} /> {item}</li>)}</ul></div><div className="before-after"><div className="before"><span>Before</span><h3>Scattered reports</h3><div className="messy-lines" /></div><div className="after"><span>After</span><h3>One clear view</h3><div className="mini-bars"><i /><i /><i /><i /><i /></div></div></div></div></section>
    <section id="contact" className="cta shell"><div><p className="eyebrow">Ready when you are</p><h2>Make data your unfair advantage.</h2><p>Book a free 30-minute audit. We’ll show you where you’re losing money—and how to fix it.</p></div><a className="button" href="mailto:hello@datavision.agency">Book free audit <ArrowUpRight size={18} /></a></section><footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">D</span> DataVision</a><span>Analytics that earns its keep.</span><span>© 2026 DataVision</span></footer>
  </main>
}
function SectionIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="section-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div> }
function DashboardPreview() { return <div className="dashboard-wrap"><div className="dashboard-card"><div className="dashboard-head"><span>Revenue intelligence</span><span className="live"><i /> Live</span></div><div className="kpi-row"><div><small>Net revenue</small><strong>$284,920</strong><span className="positive">↗ 32.8%</span></div><div><small>Forecast confidence</small><strong>94.2%</strong><span className="positive">↗ 8.4%</span></div></div><div className="chart"><div className="chart-grid" /><svg viewBox="0 0 420 150" preserveAspectRatio="none"><path d="M0 130 C35 120 45 90 75 102 S120 118 150 82 S195 105 225 64 S270 72 300 45 S350 50 375 18 S405 28 420 4" fill="none" stroke="url(#line)" strokeWidth="4" strokeLinecap="round" /><defs><linearGradient id="line" x1="0" x2="1"><stop stopColor="#22d3ee" /><stop offset="1" stopColor="#6366f1" /></linearGradient></defs></svg></div><div className="dashboard-foot"><span>Performance trend</span><span>Last 30 days <ArrowUpRight size={13} /></span></div></div></div> }
export default App
